(ns ptc.tbl
  "Frob JMS messages into upload actions and workflow parameters.")

(def http-url-keys
  "JMS message keys that name HTTP URLs."
  [:cromwellBaseUrl
   :mercuryFingerprintStoreURI])

(def gcs-keys
  "JMS message keys that name GCS cloud paths."
  [:analysisCloudPath
   :cloudChipMetaDataDirectory
   :cloudGreenIdatPath
   :cloudRedIdatPath
   :controlDataDirectory
   :cromwellBaseExecutionCloudPath
   :monitoringScriptPath
   :vaultTokenPath])

(def nfs-keys
  "JMS message keys that name NFS filesystem paths."
  [:analysisDirectory
   :beadPoolManifestPath
   :bsMap
   :bwa
   :bwa64
   :bwaMem
   :bwaMem_0_7_15
   :chipManifestPath
   :clioClientJarPath
   :cloudSoftwarePath
   :clusterFilePath
   :cromwellJarPath
   :cromwellWorkflowDependenciesZip
   :cromwellWorkflowOptionsFile
   :cromwellWorkflowWdlFile
   :dbSnpFilePath
   :extraRLibsDir
   :flowcellAnalysisDirectory
   :gatk2Jar
   :haplotypeMap
   :identifyBamId
   :jarPath
   :jmsVaultPath
   :latexClassesDir
   :maq
   :mercuryFingerprintStoreCredentialsVaultPath
   :podRoot
   :referenceFasta
   :referenceResourceFile
   :samblaster
   :samtools
   :samtoolsRapidQc
   :serviceAccountJsonPath
   :serviceAccountJsonVaultPath
   :snap
   :starAligner
   :topHat])

(def other-keys
  "JMS message keys not in above collections."
  [:aggregationPendingQueue
   :analysisCloudVersion
   :blacklistSchema
   :callRateThreshold
   :chipName
   :chipWellBarcode
   :clioPort
   :clioServer
   :clioUseHttps
   :collaboratorParticipantId
   :cromwellWorkflowGoogleProject
   :cromwellWorkflowName
   :environment
   :errors
   :extendedIlluminaManifestFileName
   :extendedIlluminaManifestVersion
   :farpointQueue
   :fileNameSafeSampleAlias
   :gender
   :isPodWorkflow
   :jmsPort
   :jmsServer
   :labBatch
   :metricsSchema
   :negativeControl
   :notificationEmailAddresses
   :participantId
   :picardSchema
   :pipelineGitHash
   :pipelineVersion
   :podName
   :positiveControl
   :productFamily
   :productName
   :productOrderId
   :productPartNumber
   :rapidQcPendingAggregationQueue
   :regulatoryDesignation
   :requeryLimsForIdats
   :researchProjectId
   :sampleAlias
   :sampleId
   :sampleLsid
   :snapThreadCount
   :variantCallingRequestQueue
   :warnings])

(def all-keys
  "All the keys in the :workflow part of the JMS message."
  [:aggregationPendingQueue
   :analysisCloudPath
   :analysisCloudVersion
   :analysisDirectory
   :beadPoolManifestPath
   :blacklistSchema
   :bsMap
   :bwa
   :bwa64
   :bwaMem
   :bwaMem_0_7_15
   :callRateThreshold
   :chipManifestPath
   :chipName
   :chipWellBarcode
   :clioClientJarPath
   :clioPort
   :clioServer
   :clioUseHttps
   :cloudChipMetaDataDirectory
   :cloudGreenIdatPath
   :cloudRedIdatPath
   :cloudSoftwarePath
   :clusterFilePath
   :collaboratorParticipantId
   :controlDataDirectory
   :cromwellBaseExecutionCloudPath
   :cromwellBaseUrl
   :cromwellJarPath
   :cromwellWorkflowDependenciesZip
   :cromwellWorkflowGoogleProject
   :cromwellWorkflowName
   :cromwellWorkflowOptionsFile
   :cromwellWorkflowWdlFile
   :dbSnpFilePath
   :environment
   :errors
   :extendedIlluminaManifestFileName
   :extendedIlluminaManifestVersion
   :extraRLibsDir
   :farpointQueue
   :fileNameSafeSampleAlias
   :flowcellAnalysisDirectory
   :gatk2Jar
   :gender
   :haplotypeMap
   :identifyBamId
   :isPodWorkflow
   :jarPath
   :jmsPort
   :jmsServer
   :jmsVaultPath
   :labBatch
   :latexClassesDir
   :maq
   :mercuryFingerprintStoreCredentialsVaultPath
   :mercuryFingerprintStoreURI
   :metricsSchema
   :monitoringScriptPath
   :negativeControl
   :notificationEmailAddresses
   :participantId
   :picardSchema
   :pipelineGitHash
   :pipelineVersion
   :podName
   :podRoot
   :positiveControl
   :productFamily
   :productName
   :productOrderId
   :productPartNumber
   :rapidQcPendingAggregationQueue
   :referenceFasta
   :referenceResourceFile
   :regulatoryDesignation
   :requeryLimsForIdats
   :researchProjectId
   :samblaster
   :sampleAlias
   :sampleId
   :sampleLsid
   :samtools
   :samtoolsRapidQc
   :serviceAccountJsonPath
   :serviceAccountJsonVaultPath
   :snap
   :snapThreadCount
   :starAligner
   :topHat
   :variantCallingRequestQueue
   :vaultTokenPath
   :warnings])
