# This workflow triggers tests on PRs that targets master branch
name: Tests on Pull Requests and Master

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest

      - name: Setup Jave
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      - run: |
          clj -A:test
