# This workflow triggers tests on PRs that targets master branch
name: Tests on Pull Requests and Master

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.469'

      # Get secret from vault
      # Lifted from https://github.com/broadinstitute/gotc-deploy/'s actions
      - name: Authenticate to Gcloud
        id: gcloud
        env:
          ROLE_ID: ${{ secrets.ROLE_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          # get vault token using role-id and secret-id
          VAULT_TOKEN=$(curl \
              --request POST \
              --data "{\"role_id\":\"${ROLE_ID}\",\"secret_id\":\"${SECRET_ID}\"}" \
              ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)
          if [ -z "${VAULT_TOKEN}" ] ; then
             echo "Vault authentication failed!"
             exit 1
          fi
          echo ::add-mask::${VAULT_TOKEN}
          echo "VAULT_TOKEN=${VAULT_TOKEN}" >> $GITHUB_ENV
          # use vault token to read secret - service account json
          curl --silent -H "X-Vault-Token: ${VAULT_TOKEN}" -X GET \
               ${VAULT_ADDR}/v1/secret/dsde/gotc/dev/service-accounts/push-to-cloud-non-prod-service-account.json \
               | jq .data > sa.json
          if [ ! -s sa.json ] ; then
             echo "Retrieval of Gcloud SA credentials failed"
             exit 1
          fi
          # auth as service account
          gcloud auth activate-service-account --key-file=sa.json
          if [ $? -ne 0 ] ; then
             echo "Gcloud auth failed!"
             exit 1
          fi

      - name: Lint
        run: clojure -A:lint

      - name: Unit Test
        run: clojure -A:test unit

      - name: Integration Test
        run: clojure -A:test integration
